# U-Boot
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-stm32mp1-dhsom"
PREFERRED_PROVIDER_u-boot = "u-boot-stm32mp1-dhsom"
PREFERRED_PROVIDER_u-boot-native = "u-boot-stm32mp1-dhsom"
PREFERRED_PROVIDER_u-boot-fw-utils = "u-boot-stm32mp1-dhsom-fw-utils"
PREFERRED_PROVIDER_u-boot-fw-utils-native = "u-boot-stm32mp1-dhsom-fw-utils-native"
PREFERRED_VERSION_u-boot = "2020.07%"
PREFERRED_VERSION_u-boot-native = "2020.07%"
PREFERRED_VERSION_u-boot-fw-utils = "2020.07%"
PREFERRED_VERSION_u-boot-fw-utils-native = "2020.07%"

# Linux
PREFERRED_PROVIDER_virtual/kernel = "linux-stm32mp1-dhsom-rt"
PREFERRED_VERSION_linux-stm32mp1-dhsom = "5.4%"
