# U-Boot
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-stm32mp1-dhsom"
PREFERRED_PROVIDER_u-boot = "u-boot-stm32mp1-dhsom"
PREFERRED_PROVIDER_u-boot-native = "u-boot-stm32mp1-dhsom"
PREFERRED_PROVIDER_u-boot-fw-utils = "u-boot-stm32mp1-dhsom-fw-utils"
PREFERRED_PROVIDER_u-boot-fw-utils-native = "u-boot-stm32mp1-dhsom-fw-utils-native"
PREFERRED_VERSION_u-boot = "2021.01%"
PREFERRED_VERSION_u-boot-native = "2021.01%"
PREFERRED_VERSION_u-boot-fw-utils = "2021.01%"
PREFERRED_VERSION_u-boot-fw-utils-native = "2021.01%"

# Linux
KERNEL_DEFCONFIG = "stm32mp1_dhsom_defconfig"
PREFERRED_PROVIDER_virtual/kernel = "linux-stm32mp1-dhsom"
PREFERRED_VERSION_linux-stm32mp1-dhsom = "5.10%"
